// AUTO-GENERATED by deploy.yml for PRODUCTION
const config = {
  msalConfig: {
    auth: {
      clientId: "5727bc31-78a1-4339-a7b5-b93c085b1a9c",
      authority: "https://login.microsoftonline.com/9819563e-990b-4fab-be8f-9aab13964cbb",
      redirectUri: "https://reigen-kageno.github.io/data-entry-app/",
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: true,
    },
  },
  scopes: {
    graph: ["User.Read", "Sites.ReadWrite.All", "offline_access"],
  },
  sharePoint: {
    siteId: "soecosn.sharepoint.com,3065b849-1c3f-4414-ae4a-262c667bc402,878794f3-9fdc-446f-bdc1-779805687f00",
    lists: {
      machines: "6794d80e-561e-4aa1-9695-b62ffc516b26",
      formEntries: "8c6096b3-e014-4837-a395-7a461a6e25ca",
      stockChecks: "8f2c2330-3798-46e6-8f59-a889663b7b72",
      ventes: "3384f5a1-a69a-44e3-bcf7-72ebf37bdf58",
      production: "541bcbae-e063-44b8-b5f9-2d06276446b4",
      clientPayments: "9b461087-b720-4a77-b14f-e006e161d9f0",
      deblai: "080e3534-dce9-4622-b891-1fd7dce60e67"
    }
  },
  adminEmail: "malick.dia@soeco.sn"
};
export default config;
