name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [ main ]
  
permissions:
  contents: write        # allow pushing commits
  pages: write           # allow updating GitHub Pages
  id-token: write        # if you use OIDC for other actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Generate a config.js from your GitHub Secret
      - name: Create config.js
        run: |
          echo "// AUTO‑GENERATED" > config.js
          echo "export const SYNC_ENDPOINT_URL = '${{ secrets.SYNC_ENDPOINT_URL }}';" >> config.js

      # 2️⃣ Deploy all files (including the generated config.js)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages    # or main if you’re using docs/ folder
          publish_dir: .

